### ISSUE TITLE
Investigate intersection/annotation of "known variants" when a variant VCF from CLE for example is supplied

### ISSUE THREAD

**Issue by malachig** [wustl-oncology/analysis-wdls#103]
For some runs it is desirable to annotate variant results from the pipeline with those that were also called in another pipeline.  For example these could be variants from a CLIA/CAP pipeline and checking pipeline called variants against this "known" or "validated" set may be required for compliance.  

Currently in immuno.wdl you can supply validated variants as an input in the form of an indexed VCF
https://github.com/wustl-oncology/analysis-wdls/blob/90c4ff39c23cd432187108399e5f0996741c6885/definitions/immuno.wdl#L191-L192

The `validated_variants` input gets passed to [somatic_exome.wdl](https://github.com/wustl-oncology/analysis-wdls/blob/main/definitions/somatic_exome.wdl) and then gets passed to [detect_variants.wdl](https://github.com/wustl-oncology/analysis-wdls/blob/main/definitions/detect_variants.wdl) and then gets passed to [subworkflows/filter_vcf.wdl](https://github.com/wustl-oncology/analysis-wdls/blob/main/definitions/subworkflows/filter_vcf.wdl) and then gets passed to [tools/filter_known_variants.wdl](https://github.com/wustl-oncology/analysis-wdls/blob/main/definitions/tools/filter_known_variants.wdl).

filter_known_variants uses a series bcftools commands with the intent to perhaps annotate variants with `VALIDATED`. 

My first question was, is this actually happening?  The answer appears to be yes.  Or final VCFs include various annotations and the last three looking something like this: CSQ=<huge vep annotation>;VALIDATED;set=mutect-strelka

My first thought on this is that this does not seem to follow the convention of VCF? Seems to me that it would be more correct to define a new tag (e.g. `known_variant_status`), define this in the VCF header, and then give a value of VALIDATED or NOT_FOUND. 

It seems that while these annotations are present in the final VCF, being validated is NOT required to be in that VCF. In this example `/storage1/fs1/gillandersw/Active/Project_0001_Clinical_Trials/pancreas_leidos/analysis/TWJF-5120-02_BGA-2103/gcp_immuno/final_results/annotated.expression.vcf.gz` there are:

- 45 variants that are `VALIDATED`
- 61 that do not include this string.  And 36 of these variants are marked PASS.  I believe these are being carried forward to neoantigen prediction.  Maybe that is what we actually want to do, but we need to discuss.

While reviewing this I noticed that immuno.wdl *also* has this step that takes the final variants from somatic exome as input:
https://github.com/wustl-oncology/analysis-wdls/blob/90c4ff39c23cd432187108399e5f0996741c6885/definitions/immuno.wdl#L434-L438

These lines invoke [tools/intersect_known_variants.wdl](https://github.com/wustl-oncology/analysis-wdls/blob/main/definitions/tools/intersect_known_variants.wdl).

This sounds like the step that intends to actually remove the non validated variants if the user supplied such a list.

My interpretation of this code, is that it takes the validated VCF supplied by the user and pulls out those that are `PASS`.  And then it intersects this list with the `PASS` variants in the pipeline VCF.  This is not happening. 

When this tool intersect_known_variants.wdl is called from immuno.wdl, don't we need to pass in `validated_variants` and `validated_variants_tbi`?? Unless those are defined, it seems the intersection step is skipped and the input VCF is merely copied.

**Comment by chrisamiller** [comment]
> My first thought on this is that this does not seem to follow the convention of VCF? 
It's legit, best I can tell.  If the info field is declared as type "Flag", then it's just a presence/absence thing. and just the string is how it's represented.  For example:

```
##INFO=<ID=H2,Number=0,Type=Flag,Description="HapMap2 membership">
. . .
20     14370    rs6054257  G     A      29    PASS    NS=3;DP=14;AF=0.5;DB;H2           GT:GQ:DP:HQ  0|0:48:1:51,51  1|0:48:8:51,51   1/1:43:5:.,.```

> It seems that while these annotations are present in the final VCF, being validated is NOT required to be in that VCF.

That appears to be correct, and I think we need to decide whether the proper move is to flag those variants (as is now done) or remove them from consideration (probably by setting the FILTER field to "NONVALIDATED" or similar)

Some of this obviously raises the question of "why are we redoing variant calling if we only intend to use those variants that were provided"

**Comment by malachig** [comment]
I confirmed that this flag does seem to be documented in the VCF header. Here is an example from a recent run:
```
##INFO=<ID=VALIDATED,Number=0,Type=Flag,Description="Sites listed in VALIDATED">
```

I think we should:
- Drop use of `tools/intersect_known_variants.wdl` in immuno.wdl.  Currently it is not connected right anyway and is not actually happening
- Instead I think we should surface the information about "validated" variants based on the existing flag.  We could do this by including this information when we create a TSV from the VCF.
- We can also plan to include this information in the pvacseq aggregated epitopes json file so that it could be viewed in pVACview. 

At a high level I think it is a reasonable feature to have the concept of comparing to a set of outside variants from a CLIA/CAP assay.  In theory this could be done with the VCF we get from our local CLE lab but could also be done with variants from Tempus, BostonGene, etc.

**Comment by malachig** [comment]
Also, I think we should rename [tools/filter_known_variants.wdl](https://github.com/wustl-oncology/analysis-wdls/blob/main/definitions/tools/filter_known_variants.wdl). Its not doing any filtering.  `annotate_known_variants` would be more clear.

**Comment by malachig** [comment]
Test that adding `VALIDATED` to `immuno.variants_to_table_fields:` in an immuno YAML results in the info being dropped into the TSV.

**Comment by malachig** [comment]
Summary for a proposed change here:

- Drop use of tools/intersect_known_variants.wdl from immuno.wdl.  We don't actually want to remove variants but rather annotate them as validated or not
- Test that adding VALIDATED to immuno.variants_to_table_fields: in an immuno YAML results in the info being dropped into the TSV.
- Rename tools/filter_known_variants.wdl to annotate_known_variants.

**Comment by malachig** [comment]
This has all been completed now.
