### ISSUE TITLE
Immuno workflow annotated VCF gets written as a .vcf file instead of .vcf.gz

### ISSUE THREAD

**Issue by susannasiebert** [wustl-oncology/analysis-wdls#126]

**Comment by malachig** [comment]
It does?  Can you add more detail?

When I pull results down, the final VCF I have been looking at is `annotated.expression.vcf.gz`

**Comment by tmooney** [comment]
I did get a .gz ending when I went to the data tab of the immuno run and copied the gs:// path for `pvacseq_annotated_expression_vcf_gz` to use `gsutil cp`.  But yeah, when I click the link in the datatable Terra "helpfully" renames the file to not end `.gz`... I guess this is more an issue specifically with terra than with the WDL per se.

**Comment by susannasiebert** [comment]
yeah, I think this issue can be closed.
