### ISSUE TITLE
Minimum VAF cutoff hardcoded in the Fp Filter step

### ISSUE THREAD

**Issue by evelyn-schmidt** [wustl-oncology/analysis-wdls#165]
https://github.com/wustl-oncology/analysis-wdls/blob/de14a42344fb77a7c9cf248f6f702356eece47c9/definitions/tools/fp_filter.wdl#L14

@ksinghal28  and I discussed a problem where we felt like changing the `immuno.tdna_vaf: 0.1` cutoff in the immuno yaml file didn't seem to affect the number of variants let through. We found that this variable was still being manually set. I don't think this is the intended behavior. Should this be changed to the `tdna_vaf` variable or maybe tdna_vaf/2 for subclonal variants?

**Comment by malachig** [comment]
Note that if you want to allow more permissive variant calling with a lower tumor VAF cutoff you would do something like this in your YAML.

```
immuno.min_var_freq: 0.03
immuno.varscan_min_var_freq: 0.03
```

If you look through the WDLs you can see how these parameters get passed through immuno to somatic_exome to detect_variants and then to the individual variant callers and filtering steps.

Several tasks like that one above set a default, but this default can be overridden in your inputs YAML.  If variable has not been defined up to the highest level (immuno.wdl in this case) you might have to specify it more fully.  e.g. `immuno.somatic_exome.fp_min_var_freq = 0.03`

`immuno.tdna_vaf` is a bit of a red herring here.  It sounds relevant, but it is used entirely independently and just by the pvacseq task. It applies *additional* filtering to the variants that are passed to pVACseq. These filters just impact one report TSV file.  Adjusting this parameter can not recover variants that were already filtered out at an upstream stage (in detect variants).

**Comment by evelyn-schmidt** [comment]
This makes sense! Thank you!
